# Generated by Django 3.0.6 on 2020-05-31 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redissetting',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logs.RedisPlan'),
        ),
        migrations.AlterField(
            model_name='redissetting',
            name='max_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='max_plan', to='logs.RedisPlan'),
        ),
        migrations.AlterField(
            model_name='redissetting',
            name='min_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='min_plan', to='logs.RedisPlan'),
        ),
        migrations.AlterField(
            model_name='redissetting',
            name='scaling_rate',
            field=models.CharField(blank=True, choices=[('1 min', '1 min'), ('5 min', '5 min'), ('10 min', '10 min')], default='5 min', max_length=16, null=True),
        ),
    ]
